# Generated by Django 2.0.8 on 2018-09-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='published_date_lte',
        ),
    ]
