# Generated by Django 2.0.8 on 2018-09-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180927_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_date_lte',
            new_name='published_date',
        ),
    ]
