# Generated by Django 2.0.8 on 2018-09-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180928_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'verbose_name_plural': 'art'},
        ),
        migrations.AlterModelOptions(
            name='blocks',
            options={'verbose_name_plural': 'blocks'},
        ),
        migrations.AlterModelOptions(
            name='fashion',
            options={'verbose_name_plural': 'fashion'},
        ),
        migrations.AlterModelOptions(
            name='glamour',
            options={'verbose_name_plural': 'glamour'},
        ),
        migrations.AlterModelOptions(
            name='lifestyle',
            options={'verbose_name_plural': 'lifestyle'},
        ),
        migrations.AlterModelOptions(
            name='mostpopular',
            options={'verbose_name_plural': 'mostPopular'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name_plural': 'music'},
        ),
        migrations.AlterModelOptions(
            name='slidercard',
            options={'verbose_name_plural': 'sliderCard'},
        ),
        migrations.AlterModelOptions(
            name='topstories',
            options={'verbose_name_plural': 'topStories'},
        ),
        migrations.AlterModelOptions(
            name='travel',
            options={'verbose_name_plural': 'travel'},
        ),
        migrations.AlterModelOptions(
            name='trending',
            options={'verbose_name_plural': 'trending'},
        ),
    ]
