# Generated by Django 2.0.8 on 2018-09-29 04:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20180928_1800'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='travel',
            new_name='stories',
        ),
        migrations.AlterModelOptions(
            name='stories',
            options={'verbose_name_plural': 'stories'},
        ),
    ]
